import type { ProductTourStep } from '@/features/product-tour/types/productTour.types';

export const PRODUCT_TOUR_STEPS: ProductTourStep[] = [
  {
    id: 'home-hero',
    scope: 'core',
    route: '/dashboard',
    target: 'home-hero',
    title: 'Este es tu resumen principal',
    description: 'Acá ves rápido si tu web está generando movimiento y si ya hay datos reales para leer.',
    placement: 'bottom',
  },
  {
    id: 'home-project-card',
    scope: 'core',
    route: '/dashboard',
    target: 'home-project-card',
    title: 'Mi Proyecto',
    description: 'Desde este bloque seguís el estado de tu proyecto sin meterte en detalles técnicos.',
    placement: 'bottom',
  },
  {
    id: 'home-payments-card',
    scope: 'core',
    route: '/dashboard',
    target: 'home-payments-card',
    title: 'Pagos',
    description: 'Acá revisás tu historial y cualquier pendiente sin salir de Pulse.',
    placement: 'bottom',
  },
  {
    id: 'home-support-card',
    scope: 'core',
    route: '/dashboard',
    target: 'home-support-card',
    title: 'Soporte',
    description: 'Si necesitás ayuda, este es tu canal directo con el equipo de TuWebAI.',
    placement: 'top',
  },
  {
    id: 'pulse-metrics-grid',
    scope: 'core',
    route: '/dashboard/pulse',
    target: 'pulse-metrics-grid',
    title: 'Pulse traduce datos a lenguaje simple',
    description: 'Estas métricas resumen visitas, consultas y tendencia del período que estás mirando.',
    placement: 'bottom',
  },
  {
    id: 'pulse-period-selector',
    scope: 'core',
    route: '/dashboard/pulse',
    target: 'pulse-period-selector',
    title: 'Podés cambiar el período',
    description: 'Si querés comparar cómo viene tu web, cambiás el rango y Pulse recalcula la lectura.',
    placement: 'bottom',
  },
  {
    id: 'pulse-chart',
    scope: 'core',
    route: '/dashboard/pulse',
    target: 'pulse-chart',
    title: 'El gráfico muestra el ritmo',
    description: 'No hace falta leer GA4 crudo: acá ves si el tráfico viene creciendo, estable o flojo.',
    placement: 'top',
  },
  {
    id: 'pulse-top-pages',
    scope: 'core',
    route: '/dashboard/pulse',
    target: 'pulse-top-pages',
    title: 'También ves qué páginas atraen más atención',
    description: 'Esto te ayuda a entender qué parte de tu web está funcionando mejor.',
    placement: 'left',
  },
  {
    id: 'profile-header',
    scope: 'profile',
    route: '/dashboard/perfil',
    target: 'profile-header',
    title: 'Este es tu perfil dentro de Pulse',
    description: 'Acá actualizás tu identidad personal y la de tu negocio sin salir del producto.',
    placement: 'bottom',
  },
  {
    id: 'profile-avatar-card',
    scope: 'profile',
    route: '/dashboard/perfil',
    target: 'profile-avatar-card',
    title: 'Tu foto y tus datos principales viven acá',
    description: 'Este bloque concentra tu avatar, tu nombre y cómo se te ve en el resto de Pulse.',
    placement: 'bottom',
  },
  {
    id: 'profile-tab-datos',
    scope: 'profile',
    route: '/dashboard/perfil',
    target: 'profile-panel-datos',
    tabValue: 'datos',
    title: 'Datos personales',
    description: 'Desde esta pestaña actualizás tu nombre, teléfono y la identidad base con la que aparecés en Pulse.',
    placement: 'top',
  },
  {
    id: 'profile-form-datos',
    scope: 'profile',
    route: '/dashboard/perfil',
    target: 'profile-form-datos',
    tabValue: 'datos',
    title: 'Acá guardás tu información personal',
    description: 'Este formulario concentra nombre, teléfono y tu email de acceso dentro de Pulse.',
    placement: 'top',
  },
  {
    id: 'profile-tab-negocio',
    scope: 'profile',
    route: '/dashboard/perfil',
    target: 'profile-panel-negocio',
    tabValue: 'negocio',
    title: 'Mi negocio',
    description: 'Acá ordenás la información comercial que ayuda a contextualizar tus métricas.',
    placement: 'top',
  },
  {
    id: 'profile-form-negocio',
    scope: 'profile',
    route: '/dashboard/perfil',
    target: 'profile-form-negocio',
    tabValue: 'negocio',
    title: 'Este bloque define tu contexto comercial',
    description: 'Nombre del negocio, rubro y sitio ayudan a que Pulse lea mejor tu realidad.',
    placement: 'top',
  },
  {
    id: 'profile-tab-seguridad',
    scope: 'profile',
    route: '/dashboard/perfil',
    target: 'profile-panel-seguridad',
    tabValue: 'seguridad',
    title: 'Seguridad',
    description: 'Esta sección agrupa cambios de contraseña y acciones sensibles de acceso.',
    placement: 'top',
  },
  {
    id: 'profile-security-password',
    scope: 'profile',
    route: '/dashboard/perfil',
    target: 'profile-security-password',
    tabValue: 'seguridad',
    title: 'Desde acá cambiás tu contraseña',
    description: 'Pulse separa este cambio para que sea claro, directo y fácil de confirmar.',
    placement: 'top',
  },
  {
    id: 'profile-security-sessions',
    scope: 'profile',
    route: '/dashboard/perfil',
    target: 'profile-security-sessions',
    tabValue: 'seguridad',
    title: 'También podés cerrar todas tus sesiones',
    description: 'Si sospechás un acceso raro, este bloque te deja reiniciar la sesión en todos tus dispositivos.',
    placement: 'top',
  },
  {
    id: 'profile-tab-cuenta',
    scope: 'profile',
    route: '/dashboard/perfil',
    target: 'profile-panel-cuenta',
    tabValue: 'cuenta',
    title: 'Cuenta',
    description: 'La zona de cuenta concentra acciones delicadas, como pedir la baja a TuWebAI.',
    placement: 'top',
  },
  {
    id: 'profile-danger-zone',
    scope: 'profile',
    route: '/dashboard/perfil',
    target: 'profile-danger-zone',
    tabValue: 'cuenta',
    title: 'La zona de peligro está aislada a propósito',
    description: 'Las acciones sensibles quedan separadas del resto para evitar errores y mantener contexto.',
    placement: 'top',
  },
  {
    id: 'settings-tab-general',
    scope: 'settings',
    route: '/dashboard/configuracion',
    target: 'settings-panel-general',
    tabValue: 'general',
    title: 'Cuenta',
    description: 'Esta pestaña resume la identidad principal de tu cuenta y los datos base de acceso.',
    placement: 'bottom',
  },
  {
    id: 'settings-general-overview',
    scope: 'settings',
    route: '/dashboard/configuracion',
    target: 'settings-general-overview',
    tabValue: 'general',
    title: 'Este resumen te ubica rápido',
    description: 'Acá ves tu identidad principal, el sitio vinculado y el estado general de la cuenta.',
    placement: 'bottom',
  },
  {
    id: 'settings-tab-rendimiento',
    scope: 'settings',
    route: '/dashboard/configuracion',
    target: 'settings-panel-rendimiento',
    tabValue: 'rendimiento',
    title: 'Experiencia',
    description: 'Acá controlás cómo se siente Pulse: animaciones y modo de bajo ancho de banda.',
    placement: 'top',
  },
  {
    id: 'settings-performance-controls',
    scope: 'settings',
    route: '/dashboard/configuracion',
    target: 'settings-performance-controls',
    tabValue: 'rendimiento',
    title: 'Estos controles sí impactan tu experiencia real',
    description: 'Desde acá ajustás comportamiento visual y rendimiento dentro del dashboard.',
    placement: 'top',
  },
  {
    id: 'settings-tab-notificaciones',
    scope: 'settings',
    route: '/dashboard/configuracion',
    target: 'settings-panel-notificaciones',
    tabValue: 'notificaciones',
    title: 'Notificaciones',
    description: 'En esta pestaña elegís qué novedades querés recibir y cuáles no.',
    placement: 'top',
  },
  {
    id: 'settings-notifications-controls',
    scope: 'settings',
    route: '/dashboard/configuracion',
    target: 'settings-notifications-controls',
    tabValue: 'notificaciones',
    title: 'Acá definís qué avisos querés recibir',
    description: 'Pulse te deja elegir novedades de consultas, resúmenes y avances del proyecto.',
    placement: 'top',
  },
  {
    id: 'settings-tab-seguridad',
    scope: 'settings',
    route: '/dashboard/configuracion',
    target: 'settings-panel-seguridad',
    tabValue: 'seguridad',
    title: 'Seguridad',
    description: 'Esta parte concentra el control de sesión y las decisiones de protección disponibles hoy.',
    placement: 'top',
  },
  {
    id: 'settings-security-controls',
    scope: 'settings',
    route: '/dashboard/configuracion',
    target: 'settings-security-controls',
    tabValue: 'seguridad',
    title: 'El control de sesión vive acá',
    description: 'Este bloque te deja decidir cuánto tiempo mantener activa la sesión en este dispositivo.',
    placement: 'top',
  },
  {
    id: 'project-header',
    scope: 'project',
    route: '/dashboard/proyecto',
    target: 'project-header',
    title: 'Acá seguís tu entrega',
    description: 'Este resumen te ubica rápido en qué etapa está tu proyecto y qué deberías mirar ahora.',
    placement: 'bottom',
  },
  {
    id: 'project-stats',
    scope: 'project',
    route: '/dashboard/proyecto',
    target: 'project-stats',
    title: 'El estado general aparece resumido',
    description: 'Estas métricas te muestran cuántos proyectos tenés visibles y cómo viene el avance general.',
    placement: 'bottom',
  },
  {
    id: 'project-list',
    scope: 'project',
    route: '/dashboard/proyecto',
    target: 'project-list',
    title: 'Cada proyecto vive en su propia tarjeta',
    description: 'Desde acá podés abrir detalles, revisar el estado y seguir lo que falta sin perderte.',
    placement: 'top',
  },
  {
    id: 'support-header',
    scope: 'support',
    route: '/dashboard/soporte',
    target: 'support-header',
    title: 'Soporte concentra tu conversación con TuWebAI',
    description: 'Este módulo te deja seguir consultas, respuestas y nuevos pedidos en un solo lugar.',
    placement: 'bottom',
  },
  {
    id: 'support-summary',
    scope: 'support',
    route: '/dashboard/soporte',
    target: 'support-summary',
    title: 'Acá ves el estado de tus tickets',
    description: 'El resumen te muestra rápido qué está abierto, en progreso o ya cerrado.',
    placement: 'bottom',
  },
  {
    id: 'support-form',
    scope: 'support',
    route: '/dashboard/soporte',
    target: 'support-form',
    title: 'Desde este bloque creás una consulta nueva',
    description: 'Cuando necesitás ayuda, acá escribís el tema y Pulse lo envía al equipo.',
    placement: 'top',
  },
  {
    id: 'support-tickets',
    scope: 'support',
    route: '/dashboard/soporte',
    target: 'support-chat-launcher',
    title: 'Este chat concentra tus conversaciones',
    description: 'Acá retomás tickets activos desde el chat de soporte, sin duplicar historial en la pantalla.',
    placement: 'top',
  },
];
